# cotire.cmake 1.7.8 generated file
# /data/share/xlsx_cfg_prj/Debug/ccp_read_cfg_prj/main_prj_CXX_cotire.cmake
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_EXTENSIONS "inc;inl;ipp")
set (COTIRE_ADDITIONAL_PREFIX_HEADER_IGNORE_PATH "")
set (COTIRE_CLEAN_ALL_TARGET_NAME "clean_cotire")
set (COTIRE_CLEAN_TARGET_SUFFIX "_clean_cotire")
set (COTIRE_CMAKE_MODULE_FILE "/data/share/xlsx_cfg_prj/CMake/cotire.cmake")
set (COTIRE_CMAKE_MODULE_VERSION "1.7.8")
set (COTIRE_DEBUG "OFF")
set (COTIRE_INTDIR "cotire")
set (COTIRE_MAXIMUM_NUMBER_OF_UNITY_INCLUDES "0")
set (COTIRE_MINIMUM_NUMBER_OF_TARGET_SOURCES "3")
set (COTIRE_PCH_ALL_TARGET_NAME "all_pch")
set (COTIRE_PCH_TARGET_SUFFIX "_pch")
set (COTIRE_PREFIX_HEADER_FILENAME_SUFFIX "_prefix")
set (COTIRE_TARGETS_FOLDER "cotire")
set (COTIRE_TARGET_COMPILE_DEFINITIONS_DEBUG "DEBUG")
set (COTIRE_TARGET_COMPILE_FLAGS_DEBUG "-std=c++11;-g;-Wall;-pthread;-Werror;-fno-builtin-malloc;-fno-builtin-calloc;-fno-builtin-realloc;-fno-builtin-free;-g")
set (COTIRE_TARGET_CONFIGURATION_TYPES "Debug")
set (COTIRE_TARGET_CXX_COMPILER_LAUNCHER "COTIRE_TARGET_CXX_COMPILER_LAUNCHER-NOTFOUND")
set (COTIRE_TARGET_IGNORE_PATH "/data/share/xlsx_cfg_prj")
set (COTIRE_TARGET_INCLUDE_DIRECTORIES_DEBUG "/data/share/xlsx_cfg_prj/system;/data/share/xlsx_cfg_prj/../external/include;/data/share/xlsx_cfg_prj/../external/include/mysql_connector/include;/data/share/xlsx_cfg_prj/after;/data/share/xlsx_cfg_prj;/data/share/xlsx_cfg_prj/ccp_read_cfg_prj/system;/data/share/xlsx_cfg_prj/ccp_read_cfg_prj/../external/include;/data/share/xlsx_cfg_prj/ccp_read_cfg_prj/../external/include/mysql_connector/include;/data/share/xlsx_cfg_prj/ccp_read_cfg_prj/after;/data/share/xlsx_cfg_prj/ccp_read_cfg_prj")
set (COTIRE_TARGET_INCLUDE_PRIORITY_PATH "")
set (COTIRE_TARGET_LANGUAGE "CXX")
set (COTIRE_TARGET_MAXIMUM_NUMBER_OF_INCLUDES "")
set (COTIRE_TARGET_POST_UNDEFS "")
set (COTIRE_TARGET_PRE_UNDEFS "")
set (COTIRE_TARGET_SOURCES "/data/share/xlsx_cfg_prj/ccp_read_cfg_prj/main.cc;/data/share/xlsx_cfg_prj/ccp_read_cfg_prj/mysql_connecter.cc")
set (COTIRE_UNITY_BUILD_ALL_TARGET_NAME "all_unity")
set (COTIRE_UNITY_BUILD_TARGET_SUFFIX "_unity")
set (COTIRE_UNITY_OUTPUT_DIRECTORY "")
set (COTIRE_UNITY_SOURCE_EXCLUDE_EXTENSIONS "m;mm")
set (COTIRE_UNITY_SOURCE_FILENAME_SUFFIX "_unity")
set (CMAKE_GENERATOR "Unix Makefiles")
set (CMAKE_BUILD_TYPE "Debug")
set (CMAKE_CXX_COMPILER_ID "GNU")
set (CMAKE_CXX_COMPILER_VERSION "4.8.4")
set (CMAKE_CXX_COMPILER "/usr/bin/c++")
set (CMAKE_CXX_COMPILER_ARG1 "")
set (CMAKE_INCLUDE_FLAG_CXX "-I")
set (CMAKE_INCLUDE_SYSTEM_FLAG_CXX "-isystem ")
set (CMAKE_CXX_SOURCE_FILE_EXTENSIONS "C;M;c++;cc;cpp;cxx;m;mm;CPP")
